name: Job Bot

on:
  schedule:
    # Runs every day at 8am UTC
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allows manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use any Python version your bot requires

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the bot
    - name: Run job bot
      run: python job_bot.py
